services:

  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      # Sync host & container files for hot reloading
      - ./frontend:/app

      # Prevent syncing of node_modules
      # (this prevents issues due to host/container OS differences & improves performance)
      - /app/node_modules

    environment:
      - WATCHPACK_POLLING=true # Enable hot reloading
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://localhost:8080/api/v1

  api:
    build: ./backend
    ports:
      - 8080:8080
    secrets:
      - db.properties
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 50

secrets:
  db.properties:
    file: .env

