services:
  api:
    image: public.ecr.aws/f0d1e9f6/lacey-bees-book-inventory-image-repo:latest
    ports:
      - "8080:8080"
    secrets:
      - db.properties
    depends_on:
      db:
        condition: service_healthy
  db:
    image: arm64v8/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 50
    volumes:
      - ~/backup.sql:/docker-entrypoint-initdb.d/backup.sql
secrets:
  db.properties:
    file: .env.production

