# keep non-test configs in "default" spring profile to ensure they don't get picked up for integration test runs.
spring:
  application:
    name: lacey-bees-book-inventory-api
  config:
    import: file:/run/secrets/db.properties
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
log:
  level:
    com.nickesqueda.laceybeesbookinventoryapi: INFO
