spring:
  application:
    name: lacey-bees-book-inventory-api
  config:
    import: file:/run/secrets/db.properties
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
