name: PROD Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # Required for requesting a JWT from the GH OIDC Provider
  contents: read  # Required for actions

jobs:
  push_api_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Set up QEMU # Allows GitHub Runner to emulate arm64 (for creating cross-platform builds)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx # To create cross-platform Docker images
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials # For assuming an AWS Role capable of pushing to ECR 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050165509:role/github-actions-role
          aws-region: us-east-1

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install

      - name: Build and Push Multi-Arch Docker Image
        run: |
          export REPO_URI=public.ecr.aws/f0d1e9f6/lacey-bees-book-inventory-image-repo
          docker buildx build --platform linux/amd64,linux/arm64 -t $REPO_URI:latest --push ./backend
